/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.altriaa.buku.View;

import com.altriaa.buku.Controller.ProductController;
/**
 *
 * @author User
 */
public class ProductFormUser extends javax.swing.JFrame {
    
    ProductController controller;
    
    /**
     * Creates new form ProductFormUser
     */
    public ProductFormUser() {
        controller = new ProductController();
        initComponents();
        loadDBUser();
    }
    
    public ProductFormUser(String nama) {
       controller = new ProductController();
        initComponents();
        loadDBUser();
        namaUser.setText(nama);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        namaUser = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        background3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txtIDProductUser = new javax.swing.JTextField();
        txtJudulUser = new javax.swing.JTextField();
        txtGenreUser = new javax.swing.JTextField();
        txtPengarangUser = new javax.swing.JTextField();
        txtPenerbitUser = new javax.swing.JTextField();
        txtHargaUser = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        txtJilidUser = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableProduct5 = new javax.swing.JTable();
        jLabel44 = new javax.swing.JLabel();
        btnCari = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnCariNama = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        general = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        filosofi = new javax.swing.JButton();
        kuliner = new javax.swing.JButton();
        selfImprovement = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        kriminal = new javax.swing.JButton();
        misteri = new javax.swing.JButton();
        fantasi = new javax.swing.JButton();
        horor = new javax.swing.JButton();
        drama = new javax.swing.JButton();
        Puisi = new javax.swing.JButton();
        manga = new javax.swing.JButton();
        komedi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 107, 28), 5));
        jPanel4.setToolTipText("");

        judul.setFont(new java.awt.Font("Futura Md BT", 0, 24)); // NOI18N
        judul.setText("WELCOME");

        namaUser.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        namaUser.setText("NAMA USER");

        btnLogOut.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        btnLogOut.setText("Logout");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(namaUser)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 25, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(judul)
                                .addGap(58, 58, 58))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(judul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogOut)
                .addGap(20, 20, 20))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 107, 28), 5));

        background3.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Dokumen\\NetBeansProjects\\Buku\\src\\main\\java\\com\\altriaa\\buku\\Image\\bgbuku.jpg")); // NOI18N

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 107, 28), 5, true));

        jLabel37.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N
        jLabel37.setText("ID Buku");

        jLabel38.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N
        jLabel38.setText("Judul Buku");

        jLabel39.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N
        jLabel39.setText("Genre");

        jLabel40.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N
        jLabel40.setText("Pengarang");

        jLabel41.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N
        jLabel41.setText("Penerbit");

        jLabel42.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N
        jLabel42.setText("Harga");

        txtIDProductUser.setEditable(false);
        txtIDProductUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDProductUserActionPerformed(evt);
            }
        });

        txtJudulUser.setEditable(false);
        txtJudulUser.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtJudulUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJudulUserActionPerformed(evt);
            }
        });

        txtGenreUser.setEditable(false);
        txtGenreUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenreUserActionPerformed(evt);
            }
        });

        txtPengarangUser.setEditable(false);
        txtPengarangUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPengarangUserActionPerformed(evt);
            }
        });

        txtPenerbitUser.setEditable(false);
        txtPenerbitUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPenerbitUserActionPerformed(evt);
            }
        });

        txtHargaUser.setEditable(false);
        txtHargaUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaUserActionPerformed(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N
        jLabel43.setText("Jilid");

        txtJilidUser.setEditable(false);
        txtJilidUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJilidUserActionPerformed(evt);
            }
        });

        tableProduct5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Buku", "Genre", "Judul", "Pengarang", "Penerbit", "Harga", "Jilid"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableProduct5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProduct5MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tableProduct5);

        jLabel44.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N
        jLabel44.setText("Cari Buku:");

        btnCari.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        btnCari.setText("ID");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnCariNama.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        btnCariNama.setText("Judul");
        btnCariNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariNamaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel44)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane6)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel37)
                                    .addComponent(jLabel38)
                                    .addComponent(jLabel39)
                                    .addComponent(jLabel40)
                                    .addComponent(jLabel41)
                                    .addComponent(jLabel42)
                                    .addComponent(jLabel43))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHargaUser)
                                    .addComponent(txtPenerbitUser)
                                    .addComponent(txtPengarangUser)
                                    .addComponent(txtGenreUser)
                                    .addComponent(txtJudulUser)
                                    .addComponent(txtIDProductUser)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtJilidUser, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCariNama, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(19, 19, 19))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(txtIDProductUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38)
                    .addComponent(txtJudulUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39)
                    .addComponent(txtGenreUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addComponent(txtPengarangUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel41)
                    .addComponent(txtPenerbitUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel42)
                    .addComponent(txtHargaUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(txtJilidUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel44)
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCari)
                    .addComponent(btnClear)
                    .addComponent(btnCariNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtIDProductUser.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(background3, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 107, 28), 5));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Genre");

        general.setText("General");
        general.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generalActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Non-Fiksi");

        filosofi.setText("Filosofi");
        filosofi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filosofiActionPerformed(evt);
            }
        });

        kuliner.setText("Kuliner");
        kuliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kulinerActionPerformed(evt);
            }
        });

        selfImprovement.setText("Self Improvement");
        selfImprovement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selfImprovementActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Fiksi");

        kriminal.setText("Kriminal");
        kriminal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kriminalActionPerformed(evt);
            }
        });

        misteri.setText("Misteri");
        misteri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                misteriActionPerformed(evt);
            }
        });

        fantasi.setText("Fantasi");
        fantasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fantasiActionPerformed(evt);
            }
        });

        horor.setText("Horor");
        horor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hororActionPerformed(evt);
            }
        });

        drama.setText("Drama");
        drama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dramaActionPerformed(evt);
            }
        });

        Puisi.setText("Puisi");
        Puisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PuisiActionPerformed(evt);
            }
        });

        manga.setText("Manga");
        manga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mangaActionPerformed(evt);
            }
        });

        komedi.setText("Komedi");
        komedi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                komediActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(general)
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(79, 79, 79))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jLabel10))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel9))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(selfImprovement, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(kuliner)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(filosofi))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(horor)
                                            .addGap(102, 102, 102))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addComponent(fantasi)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                    .addComponent(kriminal)
                                                    .addGap(18, 18, 18)))
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(drama)
                                                .addComponent(komedi)
                                                .addComponent(Puisi)
                                                .addComponent(manga))))
                                    .addComponent(misteri))
                                .addGap(6, 6, 6)))
                        .addGap(16, 16, 16))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(general)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kuliner)
                    .addComponent(filosofi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selfImprovement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manga)
                    .addComponent(kriminal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(misteri)
                    .addComponent(Puisi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drama)
                    .addComponent(fantasi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(horor)
                    .addComponent(komedi))
                .addGap(323, 323, 323))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        Login log = new Login();
        setVisible(false);
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void tableProduct5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProduct5MouseClicked
        // TODO add your handling code here:
        controller.clickUser(this);
    }//GEN-LAST:event_tableProduct5MouseClicked

    private void txtIDProductUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDProductUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDProductUserActionPerformed

    private void txtJudulUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJudulUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJudulUserActionPerformed

    private void txtGenreUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenreUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenreUserActionPerformed

    private void txtPengarangUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPengarangUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPengarangUserActionPerformed

    private void txtPenerbitUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPenerbitUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPenerbitUserActionPerformed

    private void txtHargaUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaUserActionPerformed

    private void txtJilidUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJilidUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJilidUserActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        controller.cariUser(this);
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        controller.opsiGeneralUser(this);
    }//GEN-LAST:event_btnClearActionPerformed

    private void generalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generalActionPerformed
        // TODO add your handling code here:
        controller.opsiGeneralUser(this);
    }//GEN-LAST:event_generalActionPerformed

    private void filosofiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filosofiActionPerformed
        // TODO add your handling code here:
        controller.opsiFilosofiUser(this);
    }//GEN-LAST:event_filosofiActionPerformed

    private void kulinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kulinerActionPerformed
        // TODO add your handling code here:
        controller.opsiKulinerUser(this);
    }//GEN-LAST:event_kulinerActionPerformed

    private void selfImprovementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selfImprovementActionPerformed
        // TODO add your handling code here:
        controller.opsiSelfImprovementUser(this);
    }//GEN-LAST:event_selfImprovementActionPerformed

    private void kriminalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kriminalActionPerformed
        // TODO add your handling code here:
        controller.opsiKriminalUser(this);
    }//GEN-LAST:event_kriminalActionPerformed

    private void misteriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_misteriActionPerformed
        // TODO add your handling code here:
        controller.opsiMisteriUser(this);
    }//GEN-LAST:event_misteriActionPerformed

    private void fantasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fantasiActionPerformed
        // TODO add your handling code here:
        controller.opsiFantasiUser(this);
    }//GEN-LAST:event_fantasiActionPerformed

    private void hororActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hororActionPerformed
        // TODO add your handling code here:
        controller.opsiHororUser(this);
    }//GEN-LAST:event_hororActionPerformed

    private void dramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dramaActionPerformed
        // TODO add your handling code here:
        controller.opsiDramaUser(this);
    }//GEN-LAST:event_dramaActionPerformed

    private void PuisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PuisiActionPerformed
        // TODO add your handling code here:
        controller.opsiPuisiUser(this);
    }//GEN-LAST:event_PuisiActionPerformed

    private void mangaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mangaActionPerformed
        // TODO add your handling code here:
        controller.opsiMangaUser(this);
    }//GEN-LAST:event_mangaActionPerformed

    private void komediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_komediActionPerformed
        // TODO add your handling code here:
        controller.opsiKomediUser(this);
    }//GEN-LAST:event_komediActionPerformed

    private void btnCariNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariNamaActionPerformed
        // TODO add your handling code here:
        controller.cariNamaUser(this);
    }//GEN-LAST:event_btnCariNamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductFormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductFormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductFormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductFormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductFormUser().setVisible(true);
            }
        });
        
        
    }
    
    public void loadDBUser()
    {
        ProductController controller = new ProductController();
        controller.loadDBUser(this);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Puisi;
    private javax.swing.JLabel background3;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnCariNama;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton drama;
    private javax.swing.JButton fantasi;
    private javax.swing.JButton filosofi;
    private javax.swing.JButton general;
    private javax.swing.JButton horor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel judul;
    private javax.swing.JButton komedi;
    private javax.swing.JButton kriminal;
    private javax.swing.JButton kuliner;
    private javax.swing.JButton manga;
    private javax.swing.JButton misteri;
    private javax.swing.JLabel namaUser;
    private javax.swing.JButton selfImprovement;
    public javax.swing.JTable tableProduct5;
    public javax.swing.JTextField txtGenreUser;
    public javax.swing.JTextField txtHargaUser;
    public javax.swing.JTextField txtIDProductUser;
    public javax.swing.JTextField txtJilidUser;
    public javax.swing.JTextField txtJudulUser;
    public javax.swing.JTextField txtPenerbitUser;
    public javax.swing.JTextField txtPengarangUser;
    // End of variables declaration//GEN-END:variables
}
